# compiler
CONFIG_DEBUG=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_ASSERT=y

# kernel
CONFIG_REBOOT=y
CONFIG_IDLE_STACK_SIZE=2048

## memory
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=4096

## workqueue
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

# hardware
CONFIG_DMA=y

## gpios
CONFIG_GPIO=y

## adc
CONFIG_ADC=y

## uart
CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y

## spi
CONFIG_SPI=y

## can
CONFIG_CAN=y
CONFIG_CAN_ACCEPT_RTR=y
CONFIG_CAN_STATS=y

## rtc
CONFIG_RTC=y

## battery backed ram
CONFIG_BBRAM=y

# drivers
## disk
CONFIG_DISK_DRIVERS=y

## leds
CONFIG_LED=y

## sensors
CONFIG_SENSOR=y

## auxiliary display
CONFIG_AUXDISPLAY=y

# os services
## disk
CONFIG_DISK_ACCESS=y

## file system
CONFIG_FILE_SYSTEM=y

## logging
CONFIG_LOG=y
CONFIG_PRINTK=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=100
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=4096

### backends
CONFIG_LOG_BACKEND_RTT=y

CONFIG_LOG_BACKEND_FS=y
CONFIG_LOG_BACKEND_FS_DIR="/SD:/log"
CONFIG_LOG_BACKEND_FS_FILE_PREFIX=""
CONFIG_LOG_BACKEND_FS_FILES_LIMIT=4
CONFIG_LOG_BACKEND_FS_FILE_SIZE=262144

## shell
CONFIG_SHELL=y
CONFIG_SHELL_STACK_SIZE=4096

## settings
CONFIG_SETTINGS=y

### backends
CONFIG_SETTINGS_FILE=y
CONFIG_SETTINGS_FILE_MAX_LINES=32
CONFIG_SETTINGS_FILE_PATH="/SD:/settings"

## rtt
CONFIG_USE_SEGGER_RTT=y

## tracing
# CONFIG_TRACING=y

# ## sysview
# CONFIG_SEGGER_SYSTEMVIEW=y
# CONFIG_SEGGER_SYSVIEW_RTT_BUFFER_SIZE=32768

## input
CONFIG_INPUT=y
CONFIG_INPUT_EVENT_DUMP=y

## zbus
CONFIG_ZBUS=y
CONFIG_ZBUS_CHANNEL_NAME=y

## can open
CONFIG_CANOPEN=y
CONFIG_CANOPENNODE_CONFIG_FILE="canopen_config.h"
CONFIG_CANOPENNODE_MAINLINE_THREAD_STACK_SIZE=2048

## statistics
CONFIG_STATS=y

## state machine
CONFIG_SMF=y
CONFIG_SMF_ANCESTOR_SUPPORT=y
CONFIG_SMF_INITIAL_TRANSITION=y

# libraries
## nturt
CONFIG_NTURT=y

### system
CONFIG_NTURT_SYS=y

#### file system
CONFIG_NTURT_SYS_FS=y

#### rtc
CONFIG_NTURT_SYS_RTC=y

#### shell
CONFIG_NTURT_SHELL=y

### message
CONFIG_NTURT_MSG=y
CONFIG_NTURT_MSG_HB=y
CONFIG_NTURT_MSG_SDO_SRV=y
CONFIG_NTURT_MSG_SDO_CLI=y

### sensors
CONFIG_NTURT_SENSORS=y

# application
CONFIG_MAIN_STACK_SIZE=2048

## states
CONFIG_DANGER_MODE=y

## sensors
CONFIG_SENSORS_TOL_THRES=100

CONFIG_AMT21_READ_TRIES=10

### pedals
CONFIG_PEDAL_PLAUS=y

#### APPS
CONFIG_APPS_PLAUS=n
CONFIG_APPS_MICRO=n

#### BSE
CONFIG_BSE_MICRO=n
CONFIG_BSE_R=n
CONFIG_BSE_PLAUS=n
