# hardware
## spi
CONFIG_SPI_STM32_DMA=y

# drivers
## disk
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_SDMMC_STM32_HWFC=y

## usb
CONFIG_USB_DEVICE_DRIVER=y
CONFIG_USB_DRIVER_LOG_LEVEL_WRN=y

# os services
## file system
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FILE_SYSTEM_SHELL_BUFFER_SIZE=1024

## logging
### backend
# 32MB
CONFIG_LOG_BACKEND_FS_FILE_SIZE=33554432

### fatfs
CONFIG_FS_FATFS_LFN=y

## shell
CONFIG_SHELL_STACK_SIZE=8192

### backends
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_BACKEND_SERIAL_TX_RING_BUFFER_SIZE=64

## usb
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="NTU Racing Team rearbox"
CONFIG_USB_DEVICE_PID=0x0001
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_USB_DEVICE_LOG_LEVEL_WRN=y

### usb cdc acm
CONFIG_USB_CDC_ACM=y
CONFIG_USB_CDC_ACM_LOG_LEVEL_WRN=y

### usb msc
# CONFIG_USB_MASS_STORAGE=y
# CONFIG_USB_MASS_STORAGE_LOG_LEVEL_WRN=y

# libraries
## nturt
### system
#### file system
CONFIG_NTURT_SYS_FS_FAT_FS=y

# applications
CONFIG_SENSORS_POWER=y
