#ifndef CANOPEN_CONFIG_H_
#define CANOPEN_CONFIG_H_

#define CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE 0
#define CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC CO_CONFIG_FLAG_OD_DYNAMIC
#define CO_CONFIG_GLOBAL_FLAG_TIMERNEXT CO_CONFIG_FLAG_TIMERNEXT
#define CO_CONFIG_GLOBAL_RT_FLAG_CALLBACK_PRE 0

#define CO_CONFIG_EM                                                      \
  (CO_CONFIG_EM_PRODUCER | CO_CONFIG_EM_HISTORY | CO_CONFIG_EM_CONSUMER | \
   CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT | \
   CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC)

#define CO_CONFIG_EM_ERR_STATUS_BITS_COUNT (48 + 32)

#define CO_CONFIG_ERR_CONDITION_GENERIC                                      \
  (em->errorStatusBits[5] || CO_CONFIG_ERR_CONDITION_CURRENT ||              \
   CO_CONFIG_ERR_CONDITION_VOLTAGE || CO_CONFIG_ERR_CONDITION_TEMPERATURE || \
   CO_CONFIG_ERR_CONDITION_COMMUNICATION ||                                  \
   CO_CONFIG_ERR_CONDITION_DEV_PROFILE ||                                    \
   CO_CONFIG_ERR_CONDITION_MANUFACTURER)
#define CO_CONFIG_ERR_CONDITION_CURRENT (0)
#define CO_CONFIG_ERR_CONDITION_VOLTAGE (0)
#define CO_CONFIG_ERR_CONDITION_TEMPERATURE (0)
#define CO_CONFIG_ERR_CONDITION_COMMUNICATION \
  (em->errorStatusBits[2] || em->errorStatusBits[3])
#define CO_CONFIG_ERR_CONDITION_DEV_PROFILE (0)
#define CO_CONFIG_ERR_CONDITION_MANUFACTURER (0)

#define CO_CONFIG_HB_CONS                                               \
  (CO_CONFIG_HB_CONS_ENABLE | CO_CONFIG_HB_CONS_CALLBACK_MULTI |        \
   CO_CONFIG_HB_CONS_QUERY_FUNCT | CO_CONFIG_GLOBAL_FLAG_CALLBACK_PRE | \
   CO_CONFIG_GLOBAL_FLAG_TIMERNEXT | CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC)

#define CO_CONFIG_LSS (0)

#define CO_CONFIG_PDO                                              \
  (CO_CONFIG_RPDO_ENABLE | CO_CONFIG_TPDO_ENABLE |                 \
   CO_CONFIG_RPDO_TIMERS_ENABLE | CO_CONFIG_TPDO_TIMERS_ENABLE |   \
   CO_CONFIG_PDO_SYNC_ENABLE | CO_CONFIG_PDO_OD_IO_ACCESS |        \
   CO_CONFIG_FLAG_CALLBACK_PRE | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT | \
   CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC)

#define CO_CONFIG_STORAGE (CO_CONFIG_STORAGE_ENABLE)

#define CO_CONFIG_SYNC                                                       \
  (CO_CONFIG_SYNC_ENABLE | CO_CONFIG_SYNC_PRODUCER |                         \
   CO_CONFIG_GLOBAL_RT_FLAG_CALLBACK_PRE | CO_CONFIG_GLOBAL_FLAG_TIMERNEXT | \
   CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC)

#define CO_CONFIG_TIME                                   \
  (CO_CONFIG_TIME_ENABLE | CO_CONFIG_FLAG_CALLBACK_PRE | \
   CO_CONFIG_GLOBAL_FLAG_TIMERNEXT | CO_CONFIG_GLOBAL_FLAG_OD_DYNAMIC)

#endif  // CANOPEN_CONFIG_H_
